/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WhatWeBuildRouteImport } from './routes/what-we-build'
import { Route as WhyZocaloRouteImport } from './routes/why-zocalo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeBuildRoute = WhatWeBuildRouteImport.update({
  id: '/what-we-build',
  path: '/what-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyZocaloRoute = WhyZocaloRouteImport.update({
  id: '/why-zocalo',
  path: '/why-zocalo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/why-zocalo': typeof WhyZocaloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/why-zocalo': typeof WhyZocaloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/why-zocalo': typeof WhyZocaloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/process'
    | '/services'
    | '/what-we-build'
    | '/why-zocalo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/process'
    | '/services'
    | '/what-we-build'
    | '/why-zocalo'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/process'
    | '/services'
    | '/what-we-build'
    | '/why-zocalo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  WhatWeBuildRoute: typeof WhatWeBuildRoute
  WhyZocaloRoute: typeof WhyZocaloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-build': {
      id: '/what-we-build'
      path: '/what-we-build'
      fullPath: '/what-we-build'
      preLoaderRoute: typeof WhatWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-zocalo': {
      id: '/why-zocalo'
      path: '/why-zocalo'
      fullPath: '/why-zocalo'
      preLoaderRoute: typeof WhyZocaloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  WhatWeBuildRoute: WhatWeBuildRoute,
  WhyZocaloRoute: WhyZocaloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
